# Usa una imagen base de Node.js para construir la aplicación
FROM node:18-alpine


LABEL Name=frontend

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo package.json y package-lock.json
COPY package.json package-lock.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código de la aplicación
COPY . .


EXPOSE 4200


CMD ["npm", "run", "start"]

